### ISSUE TITLE
Could you consider publishing your extension on open-vsx ?

### ISSUE THREAD

**Issue by Benjamin-z** [nico-castell/desktop-file-support#2]
Open source and free software such as [VSCodium](https://vscodium.com/) and [CodeOSS](https://github.com/microsoft/vscode) have switched to [open-vsx](https://github.com/eclipse/openvsx) for their extensions.

To publish your extensions on open-vsx, you can follow these [steps](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

Thanks.

**Comment by nico-castell** [comment]
Hello @Benjamin-z, thanks for bringing this to my attention.

I am now in the process of claiming a **namespace** to publish this extension on the [Open VSX Registry](https://open-vsx.org/).

If things go well, the extension should be published tomorrow.

However, there is a **.vsix** package available for download on every [release](https://github.com/nico-castell/desktop-file-support/releases) so far, in case you or your team don't have access to the [Visual Studio Marketplace](https://marketplace.visualstudio.com/).

Thanks again for your help!

**Comment by nico-castell** [comment]
Hello again, I have published the [extension](https://open-vsx.org/extension/nico-castell/linux-desktop-file) in the **Open VSX Registry**.

This is the link:
[https://open-vsx.org/extension/nico-castell/linux-desktop-file](https://open-vsx.org/extension/nico-castell/linux-desktop-file)

Have a nice day!
